INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(1,'francisco','Gonzalez','fjgonmir@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(2,'vanesa','Sedeño','vanessa@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(3,'francisco','Gonzalez','fjgonmir@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(4,'vanesa','Sedeño','vanessa@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(5,'francisco','Gonzalez','fjgonmir@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(6,'vanesa','Sedeño','vanessa@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(7,'francisco','Gonzalez','fjgonmir@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(8,'vanesa','Sedeño','vanessa@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(9,'francisco','Gonzalez','fjgonmir@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(10,'vanesa','Sedeño','vanessa@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(11,'francisco','Gonzalez','fjgonmir@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(12,'vanesa','Sedeño','vanessa@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(13,'francisco','Gonzalez','fjgonmir@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(14,'vanesa','Sedeño','vanessa@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(15,'francisco','Gonzalez','fjgonmir@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(16,'vanesa','Sedeño','vanessa@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(17,'francisco','Gonzalez','fjgonmir@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(18,'vanesa','Sedeño','vanessa@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(19,'francisco','Gonzalez','fjgonmir@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(20,'vanesa','Sedeño','vanessa@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(21,'francisco','Gonzalez','fjgonmir@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(22,'vanesa','Sedeño','vanessa@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(23,'francisco','Gonzalez','fjgonmir@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(24,'vanesa','Sedeño','vanessa@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(25,'francisco','Gonzalez','fjgonmir@gmail.com','2017-08-28','');
INSERT INTO clientes(id,nombre,apellido,email,creation_at,foto)VALUES(26,'vanesa','Sedeño','vanessa@gmail.com','2017-08-28','');

INSERT INTO Producto(nombre,precio,create_at)VALUES('Panasonic pantalla LCD','25990',now());
INSERT INTO Producto(nombre,precio,create_at)VALUES('Panasonic pantalla LCD','25990',now());
INSERT INTO Producto(nombre,precio,create_at)VALUES('Panasonic pantalla LCD','25990',now());
INSERT INTO Producto(nombre,precio,create_at)VALUES('Panasonic pantalla LCD','25990',now());
INSERT INTO Producto(nombre,precio,create_at)VALUES('Panasonic pantalla LCD','25990',now());
INSERT INTO Producto(nombre,precio,create_at)VALUES('Panasonic pantalla LCD','25990',now());
INSERT INTO Producto(nombre,precio,create_at)VALUES('Panasonic pantalla LCD','25990',now());
INSERT INTO Producto(nombre,precio,create_at)VALUES('Panasonic pantalla LCD','25990',now());
INSERT INTO Producto(nombre,precio,create_at)VALUES('Panasonic pantalla LCD','25990',now());
INSERT INTO Producto(nombre,precio,create_at)VALUES('Panasonic pantalla LCD','25990',now());

INSERT INTO Facturas (descripcion,observacion,cliente_id,create_at) VALUES('Factura equipos de oficina',null,1,now());
INSERT INTO linea_factura(cantidad,factura_id,producto_id) VALUES(1,1,1);
INSERT INTO linea_factura(cantidad,factura_id,producto_id) VALUES(2,1,4);
INSERT INTO linea_factura(cantidad,factura_id,producto_id) VALUES(1,1,5);
INSERT INTO linea_factura(cantidad,factura_id,producto_id) VALUES(1,1,7);
INSERT INTO Facturas (descripcion,observacion,cliente_id,create_at) VALUES('Factura bicicleta','Alguna nota importante',1,now());
INSERT INTO linea_factura(cantidad,factura_id,producto_id) VALUES(1,1,7);
